### ISSUE TITLE
Fail to convert RAML to Swagger 2 

### ISSUE THREAD

**Issue by avoltmer** [lucybot/api-spec-converter#104]
When I run this conversion:

`api-spec-converter https://raw.githubusercontent.com/vmware/nsxraml/master/nsxvapi.raml --from=raml --to=swagger_2
`
An error is generated:

```
Fatal AssertionError: Error during convertion: false == true
    at parseBaseUri (/usr/local/lib/node_modules/api-spec-converter/node_modules/raml-to-swagger/src/index.js:67:3)
```

I suspect it has to do with the comment

`//Don't support other URI templates right now.`

**Comment by IvanGoncharov** [comment]
@avoltmer Yes, you absolutely right.
More details here: https://github.com/APIs-guru/raml-to-swagger/issues/2

**Comment by IvanGoncharov** [comment]
@avoltmer I implemented support for template parameters in path part of baseUri.
But your case is more complicated since `host` is a template parameter.
Swagger doesn't support template parameters in `host` 😞 
Moreover, I can even remove `host` since in this case:
> If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.

I can't think of any solution which produces valid Swagger file.
As a workaround, you can remove `baseUri` from RAML file and then add `schemes`, `host` and `baseUrl` in Swagger file.

**Comment by IvanGoncharov** [comment]
@avoltmer If you have idea how to correctly handle it in Swagger, feel free to reopen this issue.
